name: Crontab
on:
  schedule:
    - cron: 1 * * 1 *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          mkdir -p mkpkgs
          pwd
          ls -lha
          cat /etc/os-release

      - name: Check OS Directory
        run: |
          pwd
          ls -lha
          cd mkpkgs
          ls -lha
