name: Crontab
on:
  workflow_dispatch:
    branches:
    - master
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          mkdir -p mkpkgs
          pwd
          ls -lha
          cat /etc/os-release
          whoami

      - name: Check OS Directory
        run: |
          pwd
          ls -lha
          cd mkpkgs
          ls -lha
