name: Docker Container Example
on:
  push:
    tags:
      - '*'
    branches: [ main ]
  workflow_dispatch:
    branches:
    - master
  schedule:
    - cron: '0 2 * * *'
jobs:
  Container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dockenv/archlinux:latest
      # only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
      volumes:
        - /tmp:/mnt
      options: --cpus 1 --name arch --hostname arch
    steps:
      # 这个步骤是已经进入容器环境了
      - name: Run in Container
        run: |
          env
          cat /etc/os-release
          ls -lha /tmp
          ls -lha /mnt