name: Docker Build Ubuntu

on:
  workflow_dispatch:
    branches:
    - master
  schedule:
    - cron: '0 2 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ubuntu
  IMAGE_TAGS: "latest 22.10 22.04 21.10 21.04 20.10 20.04 18.04 16.04"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Dockerfile
      run : |
        git clone --depth 1 https://github.com/imxieke/dockenv.git
    - name: Build the Docker image
      run: |
        cd dockenv
        for tag in ${IMAGE_TAGS}; do
          docker build . -f images/${{ env.IMAGE_NAME }}/${tag}/Dockerfile -t ${{ env.REGISTRY }}/dockenv/${{ env.IMAGE_NAME }}:${tag}
        done

    - name: Login Github Package Registry
      run: |
        docker login -u ${{secrets.GH_USERNAME}} -p "${{ secrets.GH_APIKE }}" ${{ env.REGISTRY }}

    - name: Push Docker Image To Github Package
      run: |
        for tag in ${IMAGE_TAGS}; do
          docker push ${{ env.REGISTRY }}/dockenv/${{ env.IMAGE_NAME }}:${tag}
        done
