name: Docker Container Example
on:
  push:
    tags:
      - '*'
    branches: [ main ]
  workflow_dispatch:
    branches:
    - master
  schedule:
    - cron: '0 2 * * *'
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      # only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
      # volumes:
        # - ./:/mnt
      options: --cpus 1 --name node --hostname node
    steps:
      # 这个步骤是已经进入容器环境了
      - name: Check for dockerenv file
        run: |
          ls -lha /
          echo ${PATH}
          cat /etc/os-release
          node -v
          # /usr/bin/docker -v
          # /usr/bin/docker info
          # /usr/bin/docker ps
          # /usr/bin/docker run -it --rm node node -v