name: Docker Container Example
on:
  push:
    tags:
      - '*'
    branches: [ main ]
  workflow_dispatch:
    branches:
    - master
  schedule:
    - cron: '0 2 * * *'
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      # only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
      volumes:
        - ./:/mnt
      options: --cpus 1 --name node --hostname node
    steps:
      - name: Check for dockerenv file
        run: |
          ls -lha /
          docker -v
          docker info
          docker ps
          docker run -it --rm node node -v